version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 381492193842.dkr.ecr.ca-central-1.amazonaws.com
      - # Replace with this to your repository URI
      - REPOSITORY_URI=381492193842.dkr.ecr.ca-central-1.amazonaws.com/gupte-assign3-user
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images to ECR...
      # - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing definitions file...
      # Give your container name
      - DOCKER_CONTAINER_NAME=web_ecs_task
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json