steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloud-sem-2/parmar-assign3/python-app-latest', '.']
    id: 'Build Docker Image'

  # Step 2: Tag the Docker Image 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/cloud-sem-2/parmar-assign3/python-app-latest:latest']

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloud-sem-2/parmar-assign3/python-app-latest:latest']
    id: 'Push to Artifact Registry'

  # Step 4: Deploy the Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instance-groups'
      - 'managed'
      - 'update-instances'
      - '--zone=northamerica-northeast2-a'
      - '--instance-group=parmar-instance-group-manager'
      - '--version=latest'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY